### ISSUE TITLE
Could you do it in english??

### ISSUE THREAD

**Issue by yourgrandmadiscord** [spileur/shared-bot#2]
I can't read french xD

**Comment by spileur** [comment]
You can use Google Traduction 😅
Only the description of the repository is in french ^^

**Comment by yourgrandmadiscord** [comment]
really??? I thought the commands are french

**Comment by yourgrandmadiscord** [comment]
(Deprecated) The bot is no longer updated so it is incompatible with newer versions of discord.js

SharedBot is a bot developed with the discord.js module. It has several features like Moderation, Music and Fun. It is used on the SharedCode discord. It uses MongoDB for penalty storage.

**Comment by yourgrandmadiscord** [comment]
Oh ok

**Comment by yourgrandmadiscord** [comment]
Also, where do you put the mongodb string?

**Comment by yourgrandmadiscord** [comment]
OH LOL CONFIG.JSON

**Comment by spileur** [comment]
Yes that's it
And the password is to be put in the .env file

**Comment by yourgrandmadiscord** [comment]
Ok
